
-- #5  (Magnitude)

-- Find total customers by countries
select country,count(customer_key) as total_customer
from gold.dim_customers
group by country
order by total_customer desc

-- Find total customers by gender
select gender,count(distinct customer_key) as total_customer
from gold.dim_customers
group by gender

-- Find total products by category
select category, count(distinct product_key) as total_product
from gold.dim_products
group by category
order by category desc

-- Find the category that doesn't ordered
SELECT DISTINCT category 
FROM gold.dim_products

EXCEPT  -- minus 

SELECT DISTINCT category
FROM gold.fact_sales s 
LEFT JOIN gold.dim_products p 
ON s.product_key = p.product_key
group by category

-- What is the average costs in each category?
select category, avg(cost) as average_cost
from gold.dim_products
group by category
order by average_cost desc

-- What is the total revenue generated for each category?
select category, sum(sales_amount) as total_revenue
from gold.fact_sales s 
left join gold.dim_products p
on s.product_key = p.product_key
group by category
order by total_revenue desc

-- Find total revenue is generated by each customer
select p.customer_key,p.first_name,p.last_name, sum(sales_amount) as total_revenue
from gold.fact_sales s 
left join gold.dim_customers p
on s.product_key = p.customer_key
group by p.customer_key,first_name,last_name
order by total_revenue desc

-- What is the distribution of sold items across countries?
select country, sum(quantity) as total_quantity
from gold.fact_sales s
left join gold.dim_customers p
on s.customer_key = p.customer_key
group by country
order by total_quantity desc


-- #6 (Ranking)

-- Which 5 products generate the highest revenue?
select Top 5  p.product_name, sum(sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by product_name
order by total_revenue desc


-- What are the 5 worst-performing products in terms bf sales?
select top 5
p.product_name, 
sum(sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by product_name
order by total_revenue asc

